micronaut:
  application:
    name: myTransactionApp
netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    url: jdbc:sqlserver://localhost;databaseName=DEPOSIT;sendStringParametersAsUnicode=false;
    username: sa
    password: "xxx"
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver