micronaut:
  application:
    name: myTransactionApp
netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:password}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}

flyway:
  locations: filesystem:SQL/schema/migration
  user: ${datasources.default.username}
  password: ${datasources.default.password}
  schemas: testdb
  url: ${datasources.default.url}
